#  _____           _        _   ______         _   _                 
# |  __ \         | |      | | |  ____|       | | (_)                
# | |__) |__   ___| | _____| |_| |__ __ _  ___| |_ _  ___  _ __  ___ 
# |  ___/ _ \ / __| |/ / _ \ __|  __/ _` |/ __| __| |/ _ \| '_ \/ __|
# | |  | (_) | (__|   <  __/ |_| | | (_| | (__| |_| | (_) | | | \__ \
# |_|   \___/ \___|_|\_\___|\__|_|  \__,_|\___|\__|_|\___/|_| |_|___/
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.     
#
# PocketFactions v1.0.1 by Luke (TheDiamondYT)
# All rights reserved.                     
               
# Language used by the plugin
# - eng
language: eng
      
# Data provider that will be used for storing faction data.
# - yaml
provider: yaml

# Faction preferences
faction:
  create:
    broadcast: true
    log: false
  disband:
    log: false
  tag:
    maxLength: 10

